### ISSUE TITLE
Latest changes are not published on NPM

### ISSUE THREAD

**Issue by miqe** [LeSuisse/vue-dompurify-html#1490]
@LeSuisse  why aren't latest changes are not published on NPM?

**Comment by LeSuisse** [comment]
Hi,

Are you looking for something specific?

As far as I can remember there was no changes made to the 2.x version that had an impact on how the library is consumed so I did no feel the need to cut a release.

For the 3.x version (currently in the `vue-next` branch) since Vue 3 as gain traction since the last time I published a release it is likely I will soon(ish) publish a new version and mark it as `@latest`.

Does it answer your question?

**Comment by miqe** [comment]
@LeSuisse  Sorry I was referring to the 3.x `vue-next` branch as i had trouble working with the npm published one and got it to work directly building from github hence the question. 
Thanks It does answer my question!
